name: push black workflow
#
# Run the python formatting in check mode
#
on: push

jobs:
  black-check:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v1
        - uses: jpetrucciani/black-check@master
          with:
             path: .
             black_flags: '--exclude (\./F90|\.pl)'
