name: push black workflow
#
# Run the python formatting in check mode
#
on: push

jobs:
  black-check:
     runs-on: ubuntu-latest
     steps:
        - uses: jpetrucciani/black-check@master
          with:
             path: python
             black_flags: '--exclude ./F90/'
